version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-change_me_32_chars_minimum_required}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-4}
      - HEADLESS=${HEADLESS:-true}
      - CHROMIUM_EXECUTABLE_PATH=${CHROMIUM_EXECUTABLE_PATH:-}
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
    restart: unless-stopped

