# Fly.io configuration
app = "tradetron-token-generator"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  HEADLESS = "true"
  MAX_CONCURRENCY = "4"

[deploy]
  release_command = "npm run playwright:install"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

