#!/bin/bash
# TradeTron Token Generator - One-Click Installation Script
# Mac/Linux Bash Script
# Run this script: chmod +x install.sh && ./install.sh

echo "================================================"
echo "TradeTron Token Generator Installation"
echo "================================================"
echo ""

# Check if Node.js is installed
echo "Step 1: Checking Node.js installation..."
if ! command -v node &> /dev/null; then
    echo "✗ Node.js is not installed!"
    echo "Please install Node.js 20+ from https://nodejs.org/"
    echo "Then run this script again."
    exit 1
fi

NODE_VERSION=$(node --version)
echo "✓ Node.js found: $NODE_VERSION"

# Check Node.js version (should be 20+)
MAJOR_VERSION=$(echo $NODE_VERSION | sed 's/v\([0-9]*\).*/\1/')
if [ "$MAJOR_VERSION" -lt 20 ]; then
    echo "⚠ Warning: Node.js version 20+ recommended. Current version: $NODE_VERSION"
    read -p "Continue anyway? (Y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
fi

# Check npm
echo ""
echo "Step 2: Checking npm..."
if ! command -v npm &> /dev/null; then
    echo "✗ npm is not found!"
    exit 1
fi

NPM_VERSION=$(npm --version)
echo "✓ npm found: v$NPM_VERSION"

# Install dependencies
echo ""
echo "Step 3: Installing npm dependencies..."
echo "This may take 2-5 minutes..."
if ! npm install; then
    echo "✗ Failed to install dependencies!"
    echo "Trying with --legacy-peer-deps..."
    if ! npm install --legacy-peer-deps; then
        echo "✗ Installation failed!"
        exit 1
    fi
fi
echo "✓ Dependencies installed successfully"

# Install Playwright browser
echo ""
echo "Step 4: Installing Playwright Chromium browser..."
echo "This may take 1-3 minutes..."
if ! npm run playwright:install; then
    echo "✗ Failed to install Playwright browser!"
    exit 1
fi
echo "✓ Playwright browser installed successfully"

# Create .env.local file
echo ""
echo "Step 5: Setting up environment configuration..."

if [ -f ".env.local" ]; then
    echo "⚠ .env.local already exists"
    read -p "Do you want to overwrite it? (Y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env.local file"
    else
        rm .env.local
    fi
fi

if [ ! -f ".env.local" ]; then
    echo "Generating encryption key..."
    ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    
    echo ""
    echo "Default configuration:"
    echo "- Encryption Key: Auto-generated (secure random)"
    echo "- Max Concurrency: 4"
    echo "- Headless Mode: true"
    echo ""
    read -p "Enter custom encryption key (or press Enter to use auto-generated): " CUSTOM_KEY
    
    if [ ! -z "$CUSTOM_KEY" ]; then
        if [ ${#CUSTOM_KEY} -ge 32 ]; then
            ENCRYPTION_KEY=$CUSTOM_KEY
            echo "Using custom encryption key"
        else
            echo "⚠ Key must be at least 32 characters. Using auto-generated key."
        fi
    else
        echo "Using auto-generated encryption key"
    fi
    
    cat > .env.local << EOF
# Environment Variables Configuration
# Generated by installation script

# Required: Encryption key (minimum 32 characters)
ENCRYPTION_KEY=$ENCRYPTION_KEY

# Optional: Maximum concurrent jobs (default: 4)
MAX_CONCURRENCY=4

# Optional: Run browser in headless mode (default: true)
HEADLESS=true

# Optional: Custom Chromium executable path
CHROMIUM_EXECUTABLE_PATH=
EOF
    
    echo "✓ .env.local file created successfully"
    echo "⚠ IMPORTANT: Keep your ENCRYPTION_KEY secure! It encrypts all passwords."
fi

# Verify installation
echo ""
echo "Step 6: Verifying installation..."
echo "Building application..."
if ! npm run build; then
    echo "⚠ Build completed with warnings (this may be normal)"
else
    echo "✓ Build successful"
fi

# Success message
echo ""
echo "================================================"
echo "Installation Completed Successfully!"
echo "================================================"
echo ""
echo "Next steps:"
echo "1. Start the application:"
echo "   npm run dev"
echo ""
echo "2. Open your browser and visit:"
echo "   http://localhost:3000"
echo ""
echo "3. Add users via the 'Add User' page"
echo ""
read -p "Would you like to start the application now? (Y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "Starting application..."
    echo "The application will be available at http://localhost:3000"
    echo "Press Ctrl+C to stop the server"
    echo ""
    npm run dev
else
    echo ""
    echo "Installation complete! Run 'npm run dev' when ready to start."
fi

