# Railway configuration
# This file helps Railway understand your Next.js app

[build]
  builder = "nixpacks"
  buildCommand = "npm run playwright:install && npm run build"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100

